name    'tianyin-tachyon'
version '0.0.4'
source 'https://github.com/tianyin/puppet_tachyon'
author 'tianyin'
license 'Apache-2.0'
summary 'Puppet module for Tachyon (http://tachyon-project.org/)'
description 'Puppet module for deploying Tachyon (please refer to the GitHub project page for details)'
project_page 'https://github.com/tianyin/puppet_tachyon'
#issues_url 'https://github.com/tianyin/puppet_tachyon/issues'
dependency 'puppetlabs/stdlib', '>=4.6.0 <5.0.0'
#operatingsystem 'Ubuntu', '14.04'
